title: Aditya Gupta
email: adityagupta1089@gmail.com
baseurl: ""
url: "https://adityagupta1089.github.io"
github_username:  adityagupta1089
theme-dark: false
plugins: [jekyll-paginate-v2, kramdown]
markdown: kramdown

permalink: none

category_dir: 'categories'
category_title_prefix: ''

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: 'Page :num'
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  categories:
    layouts:
      - 'autopage_category.html'
    title: ':cat'
    permalink: '/category/:cat'
  collections:
    enabled: false
