title: Aditya Gupta
email: adityagupta1089@gmail.com
baseurl: ""
url: "http://adityagupta1089.github.io"
github_username:  adityagupta1089
theme-dark: false
plugins: [jekyll-paginate-v2, kramdown]
markdown: kramdown

category_dir: 'categories'
category_title_prefix: ''

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: 'Page :num'
  trail:
    before: 2
    after: 2

autopages:
  enabled: false
  categories:
    permalink: '/category/:cat'

  # Collection pages, omit to disable
  collections:
    layouts:
      - 'autopage_collection.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    permalink: '/collection/:coll'

  # Tag pages, omit to disable
  tags:
    layouts:
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
